config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users, path: '', path_names: { sign_in: 'login' }, controllers: {
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }

  devise_for :providers, path: 'providers', path_names: { sign_in: 'login'}, controllers: {
    sessions: 'providers/sessions',
    confirmations: 'providers/confirmations',
    registrations: 'providers/registrations'
  }

  devise_scope :user do
    authenticated :user do
      get 'dashboard', to: "users/dashboard#index", as: :users_authenticated_root
    end
  end

  devise_scope :provider do
    authenticated :provider do
      namespace :providers do
        get 'dashboard', to: "dashboard#index", as: :authenticated_root
      end
    end
  end

  resources :services, shallow: true do
    resources :chats, param: :token do
      resources :messages, only: :create
      get :my_chats, controller: :chats, on: :member
    end
  end

  root "pages#home"
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :provider
  has_many_attached :images
  has_many :service_categories, dependent: :delete_all
  has_many :categories, through: :service_categories
  has_many :chats, dependent: :destroy

  validates :name, :description, :slug, :categories, presence: true

  accepts_nested_attributes_for :categories, reject_if: :all_blank
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :authenticate_provider!, except: %i[ index show ]
  before_action :set_service, only: %i[ show edit destroy update]

  def index
    @services = Service.all
  end

  def new
    @service = Service.new
  end

  def create
    @service = current_provider.services.build(service_params)

    if @service.save
      redirect_to providers_authenticated_root_path, notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @service.update(service_params)
      redirect_to providers_authenticated_root_path, notice: t('.success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
  end

  def show
    @chat = Chat.new
  end

  def destroy
    @service.destroy
    redirect_to providers_authenticated_root_path, notice: t('.success')
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:name, :description, :price, :active, :slug, { :category_ids => [] },:images)
  end
end

app/views/services/_form.html.erb
<div class="row">
  <div class="col-12 col-lg-6">
    <%= simple_form_for @service do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :active %>
      <%= f.input :slug %>
      <%= f.input :images %>
      <%= f.association :categories, prompt: t('prompt.categories')%>
      <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="col-12 col-lg-6">
    <h5>Crear Items</h5>
  </div>
</div>

app/views/services/edit.html.erb
<div class="bg-white p-5">
  <h2 class="text-center mb-4"><%= title t("services.edit") %></h2>

  <%= render "form" %>
</div>

app/views/services/index.html.erb
<div class="mt-5">
  <h1 class="fs-3 fw-bold"><%= title t("services.title") %></h1>
</div>

<div class="row mt-4">
  <%= render Services::CardComponent.with_collection(@services) %>
</div>

app/views/services/new.html.erb
<div class="bg-white p-5">
  <h2 class="text-center mb-4"><%= title t("services.new") %></h2>

  <%= render "form" %>
</div>

app/views/services/show.html.erb
<h1>Service show</h1>

<%= button_to service_chats_path(@service) do %>
  <span class="show-when-enabled">Conversar con proveedor</span>
  <span class="show-when-disabled">Cargando...</span>
<% end %>