config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users, path: '', path_names: { sign_in: 'login' }, controllers: {
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }

  devise_for :providers, path: 'providers', path_names: { sign_in: 'login'}, controllers: {
    sessions: 'providers/sessions',
    confirmations: 'providers/confirmations',
    registrations: 'providers/registrations'
  }

  devise_scope :user do
    authenticated :user do
      get 'dashboard', to: "users/dashboard#index", as: :users_authenticated_root
    end
  end

  devise_scope :provider do
    authenticated :provider do
      namespace :providers do
        get 'dashboard', to: "dashboard#index", as: :authenticated_root
      end
    end
  end

  resources :services, shallow: true do
    resources :chats, param: :token do
      resources :messages, only: :create
      get :my_chats, controller: :chats, on: :member
    end
  end

  root "pages#home"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags site: "DBS" %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application_styles", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render NavBar::BaseComponent.new(current_user, current_provider) %>
    <%= render partial: "shared/flashes" %>
    <main class="container-xxl">
      <%= yield %>
    </main>
  </body>
</html>